[package]
name = "party_genre"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_party = { git = "https://github.com/misofm/party.git", rev = "d63a052247317ac2d3a9ac8f775df49bfeadc177" }
typed_set = { git = "https://github.com/unconfirmedlabs/typed_set.git", rev = "b37474cbde166b7ddf8a3b615cd89f90182ace6f" }
genre = { git = "https://github.com/misofm/genre.git", rev = "09f6882b57b19498f36fa15840cd7ed61094dc41" }
