[package]
name = "party_genre"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
partyos = { git = "https://github.com/misofm/partyos.git", rev = "841a875a4989082a0ebeb1beb464b71f9ea2bd73" }
typed_set = { git = "https://github.com/unconfirmedlabs/typed_set.git", rev = "b37474cbde166b7ddf8a3b615cd89f90182ace6f" }
genre = { git = "https://github.com/misofm/genre.git", rev = "cddf9491426723e2c468cebf40fb4231d9fb0d5a" }
